### ISSUE TITLE
有个bug，在读取文件时，因为使用相对定位__dirname而找不到_config.yml

### ISSUE THREAD

**Issue by johanazhu** [Kevin0z0/hexo-renderer-sass2#2]
代码是这里
https://github.com/Kevin0z0/hexo-renderer-sass2/blob/main/lib/renderer.js#L105
如下图
![image](https://user-images.githubusercontent.com/24203037/222660572-2d2d28e6-74eb-4ee5-943b-20ccdbcca3ea.png)

我将__dirname 改成process.cwd()，并启动，就可以

**Comment by Kevin0z0** [comment]
感谢反馈，已合并
